#!/bin/bash

#export CROSS=/opt/OSELAS.Toolchain-2016.06.1/arm-v7a-linux-gnueabihf/gcc-5.4.0-glibc-2.23-binutils-2.26-kernel-4.6-sanitized/bin/arm-v7a-linux-gnueabihf-
export CROSS=arm-none-eabi-

${CROSS}as -o imx7m4.o imx7m4.S
${CROSS}ld -Tlinker.ld -o imx7m4.elf imx7m4.o
sudo cp imx7m4.elf /srv/nfs/sid-armhf/lib/firmware/rproc-imx_rproc-fw
